# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb6ce7bb5683c2ceb890b7209a825298"
name = "AM Shipping Rates Test"
application_url = "https://am-shipping-rates-test-deploy.vercel.app/app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_shipping,write_products,write_shipping"

[auth]
redirect_urls = [ "https://am-shipping-rates-test-deploy.vercel.app/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
